Repository opt-nc/livre-or-collaborateurs-glia-slideshow, pull requests merged in 2022-11, with the labels that each got.

#80 Dsantos
  contributors/dsantos/index.html
  img/dsantos/quarkus.jpg
Labels: documentation

#81 typos
  contributors/dsantos/index.html
Labels: documentation, RUN, communication, quickfix

#84 83 http link to the website does not work http 404
  .github/workflows/pages.yml
  README.md
Labels: bug, documentation, RUN, communication, quickfix

#85 doc: fix short url
  README.md
Labels: bug, documentation
